name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - opencv-python
      - seaborn
